# This file was generated by GoReleaser. DO NOT EDIT.
cask "toba" do
  version "1.0.0"

  on_macos do
    on_intel do
      url "https://github.com/Gotcha190/ToBA/releases/download/v#{version}/toba_#{version}_darwin_x86_64.tar.gz"
      sha256 "0f99563e97c8a7e3f64efb34cb2e028b99c94af0de1184f70f284d637b179d7c"
    end
    on_arm do
      url "https://github.com/Gotcha190/ToBA/releases/download/v#{version}/toba_#{version}_darwin_arm64.tar.gz"
      sha256 "66d237301dd3fc840c25874f986361c8312674dbbdf6f85fc8f60700cad66daf"
    end
  end

  name "toba"
  desc "CLI for creating local WordPress environments with Lando"
  homepage "https://github.com/Gotcha190/ToBA"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "toba"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/toba"]
    end
  end

  # No zap stanza required

end
