# This file was generated by GoReleaser. DO NOT EDIT.
cask "toba" do
  version "1.0.0"

  on_macos do
    on_intel do
      url "https://github.com/Gotcha190/ToBA/releases/download/v#{version}/toba_#{version}_darwin_x86_64.tar.gz"
      sha256 "1818ed40dadd6f17f1b1aa61d960da82d6dae4710d6cb87c8fb3291d99e3c2d9"
    end
    on_arm do
      url "https://github.com/Gotcha190/ToBA/releases/download/v#{version}/toba_#{version}_darwin_arm64.tar.gz"
      sha256 "04dcff173ba3bf6a670ff61ed670b776e74c5e98b599098054c40e4b4d6db52c"
    end
  end

  name "toba"
  desc "CLI for creating local WordPress environments with Lando"
  homepage "https://github.com/Gotcha190/ToBA"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "toba"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/toba"]
    end
  end

  # No zap stanza required

end
