# This file was generated by the ToBA release workflow. DO NOT EDIT.
class Toba < Formula
  desc "CLI for creating local WordPress environments with Lando"
  homepage "https://github.com/Gotcha190/ToBA"
  version "1.3.0"
  license "MIT"

  on_macos do
    on_intel do
      url "https://github.com/Gotcha190/ToBA/releases/download/v1.3.0/toba_1.3.0_darwin_x86_64.tar.gz"
      sha256 "2131a3329c866063a77b0c3ee19b908f2a509f35e5b24c784a658125b51c847f"
    end
    on_arm do
      url "https://github.com/Gotcha190/ToBA/releases/download/v1.3.0/toba_1.3.0_darwin_arm64.tar.gz"
      sha256 "f52268e8065ffffd06b455d232e20afb18ac5f1330d1b05ea243b446bc52359f"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/Gotcha190/ToBA/releases/download/v1.3.0/toba_1.3.0_linux_x86_64.tar.gz"
      sha256 "221a16cfd4c985da80b922a90bf9e61734c0314da5a650f457fe08760233b3a3"
    end
    on_arm do
      url "https://github.com/Gotcha190/ToBA/releases/download/v1.3.0/toba_1.3.0_linux_arm64.tar.gz"
      sha256 "225559d3c9387a475f0fc2482683a4c1f0dd3a35a74468f14cab5ceeb4b65d58"
    end
  end

  def install
    bin.install "toba"
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/toba version")
  end
end
