# This file was generated by the ToBA release workflow. DO NOT EDIT.
class Toba < Formula
  desc "CLI for creating local WordPress environments with Lando"
  homepage "https://github.com/Gotcha190/ToBA"
  version "1.0.0"
  license "MIT"

  on_macos do
    on_intel do
      url "https://github.com/Gotcha190/ToBA/releases/download/v1.0.0/toba_1.0.0_darwin_x86_64.tar.gz"
      sha256 "0f30d6d2e967d340aafef09887ed98fba39f40432cf7b2fe78e7d4daf09dad45"
    end
    on_arm do
      url "https://github.com/Gotcha190/ToBA/releases/download/v1.0.0/toba_1.0.0_darwin_arm64.tar.gz"
      sha256 "99fdaf8a277b9c47444c2b31a4015b0f21e37b8c21b835e32ccc8d92e8105049"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/Gotcha190/ToBA/releases/download/v1.0.0/toba_1.0.0_linux_x86_64.tar.gz"
      sha256 "d02a4b2e10e11316da068b8e0e845e5d515b6336fad5f73bcdab4e7413ef14c8"
    end
    on_arm do
      url "https://github.com/Gotcha190/ToBA/releases/download/v1.0.0/toba_1.0.0_linux_arm64.tar.gz"
      sha256 "2799ddd542c7e10cbae1ee18b3814bd84e57e65d9d625f9d9133dee618cd47b4"
    end
  end

  def install
    bin.install "toba"
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/toba version")
  end
end
